version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017

  server:
    build: .
    environment:
      - MONGO_URI=mongodb://mongo
      - PORT=80
    ports:
      - '80:80'
